version: '3'
services:
  
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "database_name"
      POSTGRES_PORT: "5432"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
