"""canceled table pictures

Revision ID: 6d23b27e0dff
Revises: ef2e0ca6bf90
Create Date: 2024-01-12 19:01:51.253014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d23b27e0dff'
down_revision = 'ef2e0ca6bf90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('olx_site', schema=None) as batch_op:
        batch_op.drop_column('picture')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('olx_site', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture', sa.VARCHAR(length=120), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
