"""empty message

Revision ID: 986c5a81d62e
Revises: c00ce851a1f2
Create Date: 2024-01-12 22:53:59.804415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '986c5a81d62e'
down_revision = 'c00ce851a1f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('olx_site', sa.Column('picture', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('olx_site', 'picture')
    # ### end Alembic commands ###
