""" news tables

Revision ID: a30e823fd5df
Revises: 986c5a81d62e
Create Date: 2024-01-18 14:28:48.330957

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a30e823fd5df'
down_revision = '986c5a81d62e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('olx_site', sa.Column('origin_id', sa.String(), nullable=False))
    op.add_column('olx_site', sa.Column('number_of_views', sa.Integer(), nullable=True))
    op.alter_column('olx_site', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('olx_site', 'date_registered',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('olx_site', 'date_of_last_visit',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('olx_site', 'date_posted',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_unique_constraint(None, 'olx_site', ['origin_id'])
    op.drop_column('olx_site', 'number_of_looks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('olx_site', sa.Column('number_of_looks', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'olx_site', type_='unique')
    op.alter_column('olx_site', 'date_posted',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('olx_site', 'date_of_last_visit',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('olx_site', 'date_registered',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('olx_site', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('olx_site', 'number_of_views')
    op.drop_column('olx_site', 'origin_id')
    # ### end Alembic commands ###
