""" added  table pictures

Revision ID: b05759a58fc4
Revises: 6d23b27e0dff
Create Date: 2024-01-12 19:03:20.809363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b05759a58fc4'
down_revision = '6d23b27e0dff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('olx_site', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('olx_site', schema=None) as batch_op:
        batch_op.drop_column('picture')

    # ### end Alembic commands ###
