"""empty message

Revision ID: c00ce851a1f2
Revises: b05759a58fc4
Create Date: 2024-01-12 22:53:31.728660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c00ce851a1f2'
down_revision = 'b05759a58fc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('olx_site', 'picture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('olx_site', sa.Column('picture', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
