"""empty message

Revision ID: ef2e0ca6bf90
Revises: df9aa735c685
Create Date: 2024-01-11 21:42:56.958586

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ef2e0ca6bf90'
down_revision = 'df9aa735c685'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('olx_site', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('date_registered', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('date_of_last_visit', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('date_posted', sa.DateTime(), nullable=True))
        batch_op.alter_column('phone_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_constraint('olx_site_picture_key', type_='unique')
        batch_op.create_unique_constraint(None, ['url'])
        batch_op.drop_column('registration_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('olx_site', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('olx_site_picture_key', ['picture'])
        batch_op.alter_column('phone_number',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('date_posted')
        batch_op.drop_column('date_of_last_visit')
        batch_op.drop_column('date_registered')
        batch_op.drop_column('url')

    # ### end Alembic commands ###
